# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Exemplo JAVA nativo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # Compilando com Java
    - name: Compilar o Projeto
      run: |
        cd src
        javac -cp . Main.java
        javac -cp . Teste.java
      
    # Executar o Projeto
    - name: Executando Projeto
      run: |
          cd src
          java -cp . Teste
    #Versionamento por git Runner
    - name: Versão do Projeto
      run: echo ${{github.run_number}}
    # Subir no dockerhub
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Subindo no dockerhub
      with:
          image: lucasgsilva490/aula_revisao
          tags: ${{github.run_number}}
          registry: docker.io
          dockerfile: dockerfile
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
